// pageAppWizard - Auto-generated by Click Recorder
// Generated: 2026-05-10T14:31:07.019Z

export const lbl_Finishnow = "(//span[normalize-space(text())='Finish now'])[1]";
export const lbl_Next = "(//span[normalize-space(text())='Next'])[1]";
export const lbl_Finish = "(//span[normalize-space(text())='Finish'])[1]";
