// pageHome - Auto-generated by Click Recorder
// Generated: 2026-05-10T14:31:07.010Z

export const cell_Mywork = "//td[@title='My work']";
export const lbl_Inpatient = "//span[normalize-space(text())='Inpatient']";
export const lbl_Book = "(//span[normalize-space(text())='Book'])[1]";
