// pageLogin - Auto-generated by Click Recorder
// Generated: 2026-05-10T14:31:07.008Z

export const txt_UserName = "//input[@id='UserName']";
export const txt_Password = "//input[@id='Password']";
export const btn_BtnSubmit = "(//input[@id='btnSubmit'])[1]";
