// pageRegRegistration
export const txt_Forename = "//input[@dikey='itxtForename']";
export const txt_City = "//input[@dikey='C53_tA4']";
export const cmb_Country = "//input[@title='Enter Country']";
export const btn_Finishnow = "//table//td[@title='Finish now']";
export const ico_RegRoadmapTitle = "//td[@class='Cmd_TTE'][@title='Yes']";
export const lnk_Postalcode = "//img[@title='Please enter Select address type']";
export const txt_Pincode = "//input[@id='it_C_itxtFld6']";
export const btn_Find = "//td[@title='Find']";
export const tbl_SelectRow = "//td[@title='Click to select row']";
export const txt_TelephoneHome = "//input[@title='Enter Telephone (home)']";
export const txt_TelephoneMobile = "//input[@title='Enter Telephone (mobile)']";
export const txt_TelephoneWork = "//input[@title='Enter Telephone (work)']";
export const txt_TelephoneEmail = "//input[@id='it_ThInput_C67' and @title='Enter Email address']";
export const btn_Next = "//td[@title='Next']";
export const cmb_PreferenceType = "//input[@title='Select Preference Type']";
export const btn_AddPreference = "//td[@title='Add preference to grid']";
export const cmb_CountryofBirth = "//input[@title='Select Country of Birth']";
export const txt_PlaceOfBirth_ = "//input[@title='Enter a free text value for the place of birth']";
export const cmb_Nationality = "//input[@title='Select Nationality']";
export const cmb_Religion = "//input[@title='Select Religion']";
export const cmb_SexualOrientation = "//input[@title='Select Sexual orientation']";
export const cmb_SelectEthnicity = "//input[@title='Select Ethnicity']";
export const txt_Surname = "//input[@dikey='itxtSurname']";
export const cmb_Relationship = "//input[@title='Select Relationship']";
export const cmb_RelationshipRole = "//input[@id='icyclebox_Caption_C28']";
export const btn_Add = "//td[@title='Add']";
export const cmb_SelectCareproviderType = "//input[@title='Select care provider type']";
export const btn_ClickSelectCareprovider = "//input[@title='Click to select a care provider']";
export const txt_Identifier = "//input[@title='Enter the identifier']";
export const btn_FindNow = "//td[@title='Click to execute the selected search criteria']";
export const btn_Ok = "//td[@title='Click to add the selected care providers(s)']";
export const btn_Finish = "//td[@title='Finish']";
export const cmb_PrimaryContact = "//img[@title='Select Primary Contact type']";
export const lnk_Registrationtemporary = "//span[text()='Registration - temporary']";
export const btn_Cancel = "//form[@name='iShowMessage']//td[@title='Cancel']";
