// pageHome
export const tab_Patients = "//td[@caption='Patients'][@key='TB_PATNT']";
export const tab_MyWork = "//td[@title='My work']";
export const tab_InTheatre = "//td[@title='In theatre']";
export const lnkTaskPaneMyWork = "//div[@atei='Expand Pane - My work']//span[text()='<variable>']";
export const lnkSubTaskPaneInpatient = "(//div[contains(@atei,'Inpatient')]//span[text()='<variable>'])[2]";
export const lnkSubTaskPaneInpatientWithPAT = "//div[contains(@atei,'Inpatient')]//span[text()='<variable>']";
export const lnkSubTaskPaneEmerCurrentView = "//div[contains(@atei,'Current view')]//span[text()='<variable>']";
export const lnkSubTaskPaneTheatre = "//div[contains(@atei,'Theatre')]//span[text()='<variable>']";
export const lnkSubTaskPaneMedication = "//div[contains(@atei,'Medication')]//span[text()='<variable>']";
export const lnkTaskPanePatient = "//span[normalize-space()='Find record']";
export const txt_Identifier = "//input[@title='Enter an identifier']";
export const btn_Find = "//button[@title='Click to Find']";
export const btn_Logout = "//img[@title='Exit']";
export const txt_Yes = "//td[@title='Yes']";
export const btn_Login = "//input[@id='btnSubmit']";
export const lnk_Intray = "//span[normalize-space()='In-tray']";
export const btn_Findrecord = "//span[normalize-space()='Find record']";
export const tab_Mywork = "//td[@caption='Patients'][@key='TB_PATNT']";
export const lbl_popup = "//p['Question - LORENZO']";
export const btn_Yes = "//td[@title='Yes']";
export const tab_Clinic = "(//span[@class='T_PL'][normalize-space()='Clinics'])[1]";
export const txt_Clinicname = "//input[@dikey='itxtClinicname']";
export const SelectSession = "//img[@alt='Click to select row' and @title='Click to select row']";
export const btn_OK = "//td[contains(@title,'OK')]";
export const lnk_Book = "//span[@class='T_PL' and normalize-space(text())='Book']";
export const lnk_ClinicsSubLink = "//span[normalize-space()='Edit Booking']";
export const lnk_ManageAppointmentStatus = "//li[@id='itTT_C20_4']//span[contains(@class,'T_PL')][normalize-space()='Manage Appointment Status']";
export const lnk_Theatre = "//span[normalize-space()='Theatre']";
export const lnk_BookTheatre = "//span[normalize-space()='Book']";
export const tab_Bookingdetails = "//nobr[normalize-space()='Booking details']";
export const ink_Modifybooking = "//span[normalize-space()='Modify booking']";
export const tab_Intheatre = "//td[@title='In theatre']";
export const btn_Clinicalnote = "//td[@id='ieprtab_Tab_C5_iepr_Tabs_C5_15']";
export const lnk_Createnote = "//span[normalize-space()='Create note']";
export const sli_Splittericon = "//div[@id='divSplitter']";
export const txt_Notenameverify = "//label[@dikey='ilblShowTemplateName']";
export const lnk_printnote = "//span[normalize-space()='Print note']";
export const btn_Letters = "//td[@id='ieprtab_Tab_C5_iepr_Tabs_C5_18']";
export const lnk_Createdocument = "//li[@key='MN_DOC_CREATE']";
export const lnk_printdocument = "//span[normalize-space()='Print document']";
export const txt_Formsnameverify = "//label[@dikey='lblName']";
export const lnk_Correct = "//span[normalize-space()='Correct']";
export const lnk_FormsFinalise = "//span[normalize-space()='Finalise Form']";
export const lnk_Copyform = "//span[normalize-space()='Copy form']";
export const icn_filterRiteria = "//img[@title='Select a filter criteria']";
export const cmb_Struckout = "//td[@title='Struck out' and text()='Struck out']";
export const tab_Detailstab = "//nobr[contains(., 'Details')]";
export const txt_Formstatus2 = "//textarea[@id='it_C_C13' and @dikey='txtStatus']";
export const lnk_Printform = "//span[normalize-space()='Print Form']";
export const btn_Logout_10 = "//img[@title='Exit']";
export const txt_Yes_10 = "//td[@title='Yes']";
export const btn_Logout_11 = "//img[@title='Exit']";
export const txt_Yes_11 = "//td[@title='Yes']";
export const btn_Logout_12 = "//img[@title='Exit']";
export const txt_Yes_12 = "//td[@title='Yes']";
export const lnk_EditBooking = "//li[@id='itTT_C20_67']//span[@class='T_PL'][normalize-space()='Edit booking']";
export const lnk_AdmitTaskPane = "(//span[text()='Admit'])[1]";
export const tbl_SelectRow = "//tr[@id='igRowC6_0']//img[@onkeydown='C6.RCKeyDown(0)']";
export const tbl_RequestStatus = "//span[normalize-space()='Request Status']";
export const btn_PromptYes = "//img[@id='ic_I_C0' and @title='Yes']";
export const lnk_MarkasObsolete = "//span[normalize-space()='Mark as Obsolete']";