//pageObservations
export const tab_ManageObservations = "//nobr[text()='Manage observations']"
export const txt_ObservationChart = "//input[@title='Enter the observation chart template name']"
export const btn_Search = "//input[@id='searchClick']"
export const txt_Chart = "//td[contains(text(),'<variable>')]"
export const btn_New = "//a[@title='Click to start the selected template']"
export const btn_Ok = "//input[@title='Click to start the new observation chart']"
export const btn_Edit = "//input[@title='Edit']"
export const txt_NEWS = "//span[@itemuom='IntervenAssessmentNEWSObsScore']"
export const txt_inputNEWS = "//input[@role = 'spinbutton']"
export const txt_O2Sat = "//span[@itemuom='SysObsRespiratoryOxygenationSaturationValueCC_Percentage']"
export const txt_BPSystolic = "//span[@itemuom='SysObsCardiovascBPSystolicValueCC_MillimetresOfMercury']"
export const txt_rhythm = "//span[@itemuom='SysObsRespiratoryRhythm']"
export const txt_SkinColor = "//span[@itemuom='DXC_Obs_SkinColour']/parent::td"
export const btn_SkinColor = "//span[@aria-controls = 'dxc_obs_skincolour_listbox']//span[@role = 'button']"
export const cmb_inputSkinColor = "//ul[@id= 'dxc_obs_skincolour_listbox']"
export const btn_Save = "//input[@title='Save']"
export const tab_ViewObsChart = "//nobr[text()='View observation charts']"
export const lbl_Chart = "//a[@title = '<variable>']/parent::span/parent::td"
export const lbl_Status = "(//span[@title = 'Open'])[2]"