// pageLorenzo
export const lnk_NewBornDetails = "//td[@id='NewBornDetails']//u";
export const lbl_modifyAccessPlanEntrySCL = "//span[normalize-space()='Modify access plan entry']";
export const btn_Ok = "//td[@title='Ok']";
export const lbl_ManageOffer = "(//li[contains(@caption,'Manage offer')])[6]";
// DUPLICATE (broken/truncated locator) — superseded by the txt_ExpectedLOS definition later in file; commented.
// export const txt_ExpectedLOS = "//img[@onclick="$_('C29','ImageClick')";
export const lbl_ReportListView = "//td[@id='fTb_C20']";
export const lbl_Selectrow = "//tr[@id='igRowC0_0']//img[@alt='Click to select row']";
export const lbl_Available = "//td[@title='Available']";
// DUPLICATE of chk_SelectRow (superseded by the row-specific definition later in file; unused by tests) — commented.
// export const chk_SelectRow = "(//input[@type='checkbox'])[2]";
export const lnk_Volumemanagement = "//span[text()='Volume management']";
export const lnkSubTaskPaneCreatevolume = "//span[normalize-space()='Create a volume']";
export const btn_CancelDT = "//td[@title='Cancel']";
// DUPLICATE of btn_PatientName (superseded by the img definition later in file; unused by tests) — commented.
// export const btn_PatientName = "//th[.//span[@class='k-column-title' and normalize-space()='Patient name']]";
export const lnk_Requestvolume = "//span[normalize-space()='Request volume']";
export const btn_Add = "//td[normalize-space(.)='Add']";
export const btn_Next = "//td[@title='Next']";
export const tgl_Filterby = "//td[@id='g_FBLC4']";
export const txt_Voltoday = "//td[@title='Today']";
export const tbl_OPHistoryCurrentview ="//nobr[text()='Current view']";
export const btn_Coding = "//span[normalize-space()='Coding']";
export const lnk_Code = "//span[normalize-space()='Code']";
export const btn_Close = "//a[@id='dialog_close_0']";
export const rad_Code = "//table[@id='iO_C_C12']//a[normalize-space()='Code']";
export const cmb_Category = "//img[@id='icombobox_Image_C8']";
export const cmb_Codingscheme = "//img[@id='icombobox_Image_C10']";
export const cmb_Status = "//img[@id='icombobox_Image_C39']";
export const btn_Finish = "//span[.//span[normalize-space()='F'] and contains(normalize-space(.),'Finish')]";
export const lnk_ReCode = "//span[normalize-space()='Recode']";
export const btn_Finishnowrc = "//td[@title='Finish now']";
export const img_Codeset = "//img[@id='imgCode']";
export const chk_Selectcheckbox = "//input[@type='checkbox' and @data-role='checkbox' and @aria-label='Select row']";
export const lnk_Updatecode = "//span[normalize-space()='Update code']";
export const lbl_closeAccessPlanEntrySCL = "//li[@title='Close access plan entry']";
export const cmb_Requestedby = "//input[@name='icombobox_Text_C22']";
export const cmb_Reason = "//input[@name='icombobox_Text_C24']";



export const txt_ExpectedLOS = "//img[@onclick='$_('C29','ImageClick']";
export const lnk_ViewEPR="//li[@title = 'View EPR']";
export const lnkTaskPaneCreateplacerequest="//span[normalize-space()='Place request']";
export const lnkTaskPaneModifyrequest="//span[normalize-space()='Modify request']";
export const lnkTaskPaneSuspendrequest="//span[normalize-space()='Suspend request']";
export const lnkTaskPaneReinstaterequest="//span[normalize-space()='Re-instate request']";
export const lnkTaskPaneRepeatrequest="//span[normalize-space()='Repeat request']";
export const lnkTaskPaneCancelrequest="//span[normalize-space()='Cancel request']";
export const lnkTaskPaneEnterresult="//span[text()='Enter results']";
export const lnkTaskPaneModifyresult="//span[text()='Modify results']";
export const lnkTaskPaneAuthoriseresult="//span[text()='Authorise results']";
export const lnkTaskPaneAcknowledgeresults="//span[text()='Acknowledge results']";
export const txt_RequestInfo="//td[contains(@class,'iILA_ItemText_TD')]";
export const tbl_RequestStatus = "//span[normalize-space()='Request Status']";
export const lnk_Remove ="//td[@class='Cmd_TT' and @title='Remove selection']";
export const btn_plus="//img[contains(@onclick,'E_C')]";
export const chk_SelectRow="//tr[@id='igRowC6_0']//img[@title='Click to select row']";
export const lnkTaskPaneCurrentpregnancy="//span[text()='Current pregnancy']";
export const tab_Intrapartum = "//nobr[text()='Intrapartum']";
export const tab_Postnatal = "//nobr[contains(text(),'Postnatal')]";
export const lnkTaskPaneLabouranddeliverysummary ="//span[text()='Labour and delivery summary']";
export const btn_EPRTabSclUp = "//img[contains(@src,'ieprtabscrollup')]";
export const btn_EPRTabScldown = "//img[contains(@src,'ieprtabscrolldown')]";
export const btn_Maternity = "//td[@id='ieprtab_Tab_C5_iepr_Tabs_C5_21']";
export const lbl_deliverymethod ="//label[@text='Breech']";
export const lnkmothername ="//u[contains(text(),' ')]";
export const lbl_PatientBanner ="//nobr[contains(.,'Pasid-')]";
export const btn_Cancel="//img[@id='ic_I_C3']"; 
export const lnkTaskPaneDaycare="//span[@class='T_PL' and text()='Day Care']";  
export const img_selectthecentre="//img[@title='Search and select the centre']";
export const txt_Identifier ="//input[@id='it_C_C12']";
export const btn_findnow ="//img[@id='ic_I_C17']";
export const btn_sfsOk ="//img[@id='ic_I_C18']";
export const btn_find ="//img[@id='ic_I_C26']";
export const tab_Mywork ="//td[@title='My work']";
export const chk_SelectRow1 ="//td[contains(@class,'G_DRO') and contains(@class,'hdrwd6')]";
export const btn_Sessionok ="//img[@alt='OK']";
export const lnkTaskPaneBook ="//li[@id='itTT_C20_0']//span";
export const chk_SelectRowsession ="//tr[@id = 'igRowC7_0'] //img[@title = 'Click to select row']";
export const lnkTaskPaneManageappointmentstatus ="//span[text()='Manage appointment status']"
export const lnkTaskPaneCancelappointmentstatus ="//span[normalize-space(.)='Cancel appointment status']";
export const btn_QuestionYes ="//span[@class='Cmd_AK' and text()='Y']";
export const lnkTaskPaneModifyappointmentstatus ="//span[normalize-space()='Modify appointment status']";
export const btn_QuestionNo ="//img[@title='No']";
export const lnkTaskPaneCancelbooking ="//span[normalize-space()='Cancel booking']";
export const btn_PatientName ="//img[@alt='Patient name']";
export const lnk_Fluidbalance = "//nobr[normalize-space()='Fluid balance']";
export const lnk_Initiate ="//span[normalize-space()='Initiate']";
export const lnk_Formscontinue = "//span[normalize-space()='Continue']";
export const lnk_copyentireform ="//img[@title='Click to copy entire form']";
export const lnk_MarkasObsolete = "//span[normalize-space()='Mark as Obsolete']";
