// pageAssesment Details
//export const img_LeadCareProfessional = "//img[@title='Please select to assign a lead care professional']";
//export const txt_ID = "//input[@id='it_C_itxtID']";
//export const txt_Iduser = "//input[@title='Enter the identifier']";
//export const btn_findnow = "//td[@title='Click to execute the selected search criteria']";
////export const btn_Ok = "//td[@title='Click to add the selected care providers(s)']";
//export const lst_pregnancyconfirmedby = "//div[@title='Please select the appropriate options from the list']";
// export const dte_LMP = "//td[@id='DP_IHC15' and contains(@class,'DP_IA')]CLS";
//export const cmb_BasisforagreedEDD = "//td[@class='TD_H']//input[@id='C2T_C43']";
//export const cmb_Reasonforlatebooking = "//input[@title='Please select the reason for late booking']";
//export const txt_Gravida = "//input[@title='Please enter the number of pregnancies']";
//export const txt_Parity = "//input[@title='Please enter the number of live births']";
//export const cmb_Pregnancyrisk = "//img[@title='Please select the pregnancy risk']";
//export const dte_LMP = "//td[@id='DP_IHC15' and contains(@class,'DP_IA')]CLS";
//export const cmb_BasisforagreedEDD = "//input[@type='text' and @name='C2T_C43']";
//export const cmb_Reasonforlatebooking = "//input[@title='Please select the reason for late booking']";
//export const txt_Gravida = "//input[@title='Please enter the number of pregnancies']";
//export const txt_Gravida1 = "//input[@title='Please enter the number of live births']";
//export const txt_Parity="//input[@title='Please enter the number of non-viable births']";
//export const cmb_Pregnancyrisk = "//img[@title='Please select the pregnancy risk']";