// pagePrint Note -Not used anywhere

export const btn_Searchmedication = "//span[@title='Search']";
export const txt_MedicationSearch = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const lnk_searchdrug = "//button[normalize-space()='Search drug catalogue']";
export const txt_Drugcatelogue = "//kendo-gridlayout-item//span[normalize-space(text())='paracetamol']";
export const lnk_Selectitem = "//div[@title='Select item']";
export const icn_greenicon = "(//img[contains(@src, 'icopyacrossnor24.png')])[2]";
export const txt_medication = "(//div[@class='ng-star-inserted']//textblock[.//span[contains(text(),'paracetamol')]])[1]";
export const cmb_Route = "//icombobox[@name='cboRoute']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const cmb_Dosageform = "//icombobox[@ng-reflect--tooltip='Specify dosage form']//input[@role='combobox']";
export const cmb_Dosetype = "//icombobox[@name='cboDoseType']//span[@class='k-button-icon k-icona k-i-arrow-s']";
export const cmb_Dose = "//kendo-gridlayout-item[@name='DoseLayoutRoot']//kendo-gridlayout-item[1]";
export const cmb_UOM = "//icombobox[@name='cboUOM']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const Cmb_Strength = "//icombobox[@name='cboStrength']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const cmb_Frequency = "//icombobox[@name='cboFrequency']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const btn_OK = "//button[normalize-space()='Ok']";
export const txt_MedicationSearch2 = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const txt_Drugcatelogue2 = "//kendo-gridlayout-item//span[normalize-space()='senna']";
export const txt_medication2 = "(//div[@class='ng-star-inserted']//textblock[.//span[contains(text(),'senna')]])[1]";
export const txt_MedicationSearch3 = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const txt_medication3 = "(//div[@class='ng-star-inserted']//textblock[.//span[contains(text(),'flucloxacillin')]])[1]";
export const txt_Dose = "//kendo-gridlayout-item[@name='DoseLayoutRoot']//kendo-gridlayout-item[1]";
export const btn_Finish = "//span[normalize-space()='Finish']";
export const dte_Administrativetime1 = "(//kendo-label[normalize-space()='00:00'])[1]";
export const dte_Administrativetime2 = "(//kendo-label[normalize-space()='00:00'])[3]";
export const dte_Administrativetime3 = "(//kendo-label[normalize-space()='00:00'])[5]";
export const dte_Administrativetime4 = "(//kendo-label[normalize-space()='00:00'])[7]";
export const lbl_popup_conflict = "//div[@class='messageBoxContentborder']";
export const btn_OKpopup = "//span[@title='Ok']";
export const cmb_selectreason = "(//kendo-label[@title='Select reason'])[1]";
export const txt_Dose1 = "(//input[@role='spinbutton'])[1]";
export const txt_Dose2 = "(//input[@role='spinbutton'])[2]";
export const cmb_ModClerkReason = "//icombobox[@name='cboModClerkReason']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const cmb_doserangecheck = "//kendo-combobox[@class='combo-custom-styles ng-star-inserted k-input-md k-rounded-md k-input-solid k-combobox k-input ng-untouched ng-pristine ng-valid']//button[@aria-label='Select']";
export const txt_MedicationSearch4 = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const btn_OK_10 = "//button[normalize-space()='Ok']";
