// PageAllocatetocaseload
export const ico_Referralreciveddatetime = "//img[@title='Select referral for allocation']";
export const ico_surname = "//img[@title='Select the Patient surname']";
export const btn_Lastaccessed = "//td[@class='Cmd_TTE' and @title='Click to Last accessed']";
export const Clicktoselectrow = "//td[@title='Click to select row' and contains(@onclick,'$ ('C1','RC')]";
export const btn_OK = "//td[@class='Cmd_TTE' and @title='Click to add the selected patient']";
export const btn_yes = "//span[@class='Cmd_AK' and normalize-space()='Y']";
export const btn_Findnow = "//td[@class='Cmd_TT' and @title='Click to find the selected criteria']";
export const btn_Select = "//td[@class='Cmd_TT' and @title='Click to add the selected referral service definition']";
export const ico_Caseloadprofilename = "//img[@onclick='$_('txtCLProfName','OnSFSButtonClick')']";
export const txt_Caseloadprofilename = "//input[@dikey='txtCLN']";
export const cmb_Reasonforallocation = "//input[@id='icombobox_Text_C60']";
export const btn_Add = "//td[@class='Cmd_TT' and contains(@title,'Click to add')]";
export const btn_Finish = "//span[.//span[@class='Cmd_AK' and normalize-space()='F'] and contains(normalize-space(.),'Finish')]";
export const btn_Yes = "//span[@class='Cmd_AK' and normalize-space()='Y']";
export const btn_No = "//td[@class='Cmd_TTE' and @title='No']";
export const chk_Mycaseload = "//input[@type='checkbox' and @data-role='checkbox' and @aria-label='Deselect row']";
export const txt_identifier = "//input[@title='Enter an identifier']";
export const btn_Find = "//td[@title='Click to Find']";
export const img_SelectFirstRow = "//td[@title='Click to select row']";