// pageHome
export const tab_Patients = "//td[@caption='Patients'][@key='TB_PATNT']";
export const tab_MyWork = "//td[@title='My work']";
export const tab_InTheatre = "//td[@title='In theatre']";
export const lnkTaskPaneMyWork = "//div[@atei='Expand Pane - My work']//span[text()='<variable>']";
export const lnkSubTaskPaneInpatient = "(//div[contains(@atei,'Inpatient')]//span[text()='<variable>'])[2]";
export const lnkSubTaskPaneInpatientWithPAT = "//div[contains(@atei,'Inpatient')]//span[text()='<variable>']";
export const lnkSubTaskPaneEmerCurrentView = "//div[contains(@atei,'Current view')]//span[text()='<variable>']";
export const lnkSubTaskPaneTheatre = "//div[contains(@atei,'Theatre')]//span[text()='<variable>']";
export const lnkSubTaskPaneMedication = "//div[contains(@atei,'Medication')]//span[text()='<variable>']";
export const lnkTaskPanePatient = "//span[normalize-space()='Find record']";
export const txt_Identifier = "//input[@title='Enter an identifier']";
export const btn_Find = "//button[@title='Click to Find']";
export const btn_ClinicFind = "//td[@title='Find']";
export const btn_Logout = "//img[@title='Exit']";
export const txt_Yes = "//td[@title='Yes']";
export const btn_Login = "//input[@id='btnSubmit']";
export const lnk_Intray = "//span[normalize-space()='In-tray']";
export const btn_Findrecord = "//span[normalize-space()='Find record']";
export const tab_Mywork = "//td[@caption='Patients'][@key='TB_PATNT']";
export const lbl_popup = "//p['Question - LORENZO']";
export const btn_Yes = "//td[@title='Yes']";
export const tab_Clinic = "(//span[@class='T_PL'][normalize-space()='Clinics'])[1]";
export const txt_Clinicname = "//input[@dikey='itxtClinicname']";
export const SelectSession = "//img[@alt='Click to select row' and @title='Click to select row']";
export const btn_CliOK = "//td[contains(@title,'OK')]";
export const lnk_Book = "//span[@class='T_PL' and normalize-space(text())='Book']";
export const lnk_ClinicsSubLink = "//span[normalize-space()='Edit Booking']";
export const lnk_ManageAppointmentStatus = "//li[@id='itTT_C20_4']//span[contains(@class,'T_PL')][normalize-space()='Manage Appointment Status']";
export const lnk_Theatre = "//span[normalize-space()='Theatre']";
export const lnk_BookTheatre = "//span[normalize-space()='Book']";
export const tab_Bookingdetails = "//nobr[normalize-space()='Booking details']";
export const ink_Modifybooking = "//span[normalize-space()='Modify booking']";
export const tab_Intheatre = "//td[@title='In theatre']";
export const btn_Clinicalnote = "//td[@id='ieprtab_Tab_C5_iepr_Tabs_C5_15']";
export const lnk_Createnote = "//span[normalize-space()='Create note']";
export const sli_Splittericon = "//div[@id='divSplitter']";
export const txt_Notenameverify = "//label[@dikey='ilblShowTemplateName']";
export const lnk_printnote = "//span[normalize-space()='Print note']";
export const btn_Letters = "//td[@id='ieprtab_Tab_C5_iepr_Tabs_C5_18']";
export const lnk_Createdocument = "//li[@key='MN_DOC_CREATE']";
export const lnk_printdocument = "//span[normalize-space()='Print document']";
export const txt_Formsnameverify = "//label[@dikey='lblName']";
export const lnk_Formscontinue = "//span[normalize-space()='Continue']";
export const lnk_Correct = "//span[normalize-space()='Correct']";
export const lnk_FormsFinalise = "//span[normalize-space()='Finalise Form']";
export const lnk_Copyform = "//span[normalize-space()='Copy form']";
export const icn_filterRiteria = "//img[@title='Select a filter criteria']";
export const cmb_Struckout = "//td[@title='Struck out' and text()='Struck out']";
export const tab_Detailstab = "//nobr[contains(., 'Details')]";
export const txt_Formstatus2 = "//textarea[@id='it_C_C13' and @dikey='txtStatus']";
export const lnk_Printform = "//span[normalize-space()='Print Form']";
export const btn_Logout_10 = "//img[@title='Exit']";
export const txt_Yes_10 = "//td[@title='Yes']";
export const btn_Logout_11 = "//img[@title='Exit']";
export const txt_Yes_11 = "//td[@title='Yes']";
export const btn_Logout_12 = "//img[@title='Exit']";
export const txt_Yes_12 = "//td[@title='Yes']";
export const lnkSubTaskPaneNewReport= "//span[text()='New report']";
export const ico_HeadingInfos = "//p[normalize-space(.)='Question - LORENZO']";
export const lbl_ConfirmationTexts = "//div[@id='txtMessage']";
export const btn_PopUpYes = "//td[@title='Click to confirm the cancellation of the care activity']";
export const lbl_ConfirmationText = "//div[@id='txtMessage']";
export const btn_PopUpOk = "//td[@class='Cmd_TTE'][@title='Ok']";
export const ico_HeadInfo = "//p[text()='Select document templates - LORENZO']";
export const btn_CancelDT = "//td[@title='Cancel']";
export const ico_HeadingIn = "//p[contains(., 'Warning')]";
export const lbl_ConfirmationTextss = "//div[@id='txtMessage']";
export const btn_PopUpNo = "//td[@class='Cmd_TTE'][@title='No']";
export const ico_HeadingInfo = "//p['Information - LORENZO']";
export const tbl_Verifystatus = "//td[@title='Volume dispatched']";
export const lnk_ManageAppointmentStatus = "//li[@id='itTT_C20_4']//span[contains(@class,'T_PL')][normalize-space()='Manage Appointment Status']";
export const lnk_EditBooking = "//li[@id='itTT_C20_67']//span[@class='T_PL'][normalize-space()='Edit booking']";
export const lnk_AdmitTaskPane = "//li[@id='itTT_C20_11']";
export const cmb_Entity = "//input[@id='icombobox_Text_C1']";
export const txt_Identifierc = "//input[@id='it_C_C5']";
export const btn_Findc = "//td[@title='Click to Find']";
export const btn_Okc = "//td[normalize-space(.)='OK']";
export const txt_Surnamec = "//input[@id='it_C_C7']";
export const chk_Selectcheckboxs = "//img[@title='Click to select row' and contains(@src,'g_cu.gif')]";
export const chk_Selectcheckbox = "//input[@type='checkbox' and @data-role='checkbox' and @aria-label='Select row']";
export const btn_Coding = "//span[normalize-space()='Coding']";
export const lnk_Code = "//span[normalize-space()='Code']";
export const btn_Close = "//a[@id='dialog_close_0']";
export const rad_Codes = "//table[@id='iO_C_C12']//tr[@caption='Code']";
export const cmb_Category = "//img[@id='icombobox_Image_C8']";
export const cmb_Codingscheme = "//img[@id='icombobox_Image_C10']";
export const cmb_Status = "//input[@id='icombobox_Text_C39']";
export const btn_Finish = "//span[.//span[normalize-space()='F'] and contains(normalize-space(.),'Finish')]";
export const lnk_ReCode = "//span[normalize-space()='Recode']";
export const btn_Finishnowrc = "//td[@title='Finish now']";
export const img_Codeset = "//img[@id='imgCode']";
export const chk_Selectcheckbox = "//input[@type='checkbox' and @data-role='checkbox' and @aria-label='Select row']";
export const lnk_Updatecode = "//span[normalize-space()='Update code']";
export const btn_Nextc = "//td[@title='Next']";
export const txt_Codes = "//input[@dikey='txtCode']";
export const img_But = "//img[@id='ic_I_C18']";
export const lnkTaskPanePatient = "//span[normalize-space()='Find record']";
export const txt_Surname = "//input[@dikey='itxtSurname']";
export const txt_Forename = "//input[@dikey='itxtForename']";
export const cmb_Gender = "//label[text()='Gender']";
export const lbl_Gender = "//input[@title='Enter a gender value']";
export const txt_DOB = "//input[@class='DP_TB_Text']";
export const btn_Find = "//button[@title='Click to Find']";
export const cmb_identifiertype = "//img[@title='Select an  identifier type']";
export const txt_Identifier = "//input[@title='Enter an identifier']";
export const lbl_Identifier = "//label[@title='Identifier']";
export const btn_OK = "//button[@title='Click to add the selected patient']";
export const btn_PopUpOk = "//td[@class='Cmd_TTE'][@title='Ok']";
export const btn_PopUpNo = "//td[@class='Cmd_TTE' and @title='No']";
export const btn_DocTempCancel = "//td[@title = 'Cancel']"
export const lbl_PatientBookBanner = "(//td[@class='CxtBar_TD6'])[1]";
export const lnkTaskPaneCreateRef = "//li[@id='itTT_C20_0']";
export const chk_Managereferral = "//td[@text='Manage referral']";
export const btn_AdRefMng_ok = "//button[.//td[normalize-space(.)='Ok']]";
export const btn_AdRefMng_Cancel = "//button[.//td[normalize-space(.)='Cancel']]";
export const btn_Yes = "//td[@title='Yes']";
export const tab_Patients = "//td[@caption='Patients'][@key='TB_PATNT']";