// pageManagecurrentpregnancyrecordLORENZO
export const btn_Next = "//img[@title='Next']";
export const ico_HeadingInfo = "//p[contains(text(),'Information')]";
export const btn_Finish = "//img[@title='Finish']";
export const img_LeadCareProfessional = "//img[@title='Please select to assign a lead care professional']";
export const txt_ID = "//input[@id='it_C_itxtID']";
export const txt_Iduser = "//input[@title='Enter the identifier']";
export const btn_findnow = "//td[@title='Click to execute the selected search criteria']";
export const btn_Ok = "//td[@title='Click to add the selected care providers(s)']";
export const lst_pregnancyconfirmedby = "//div[@title='Please select the appropriate options from the list']";
export const dte_LMP = "//td[@id='DP_IHC15']//input";
export const cmb_BasisforagreedEDD = "//table[@id='C2_C43']//input[@type='text']";
export const cmb_Reasonforlatebooking = "//table[@id='C2_C57']//input[@type='text']";
export const txt_Gravida = "//input[@id='iupdownbox_Value_C59']";
export const txt_Gravida1 = "//input[@id='iupdownbox_Value_C60']";
export const txt_Parity="//input[@id='iupdownbox_Value_C62']";
export const cmb_Pregnancyrisk = "//input[@id='C2T_C64']";
export const cmb_FolicacidTaken ="//table[@id='C2_C28']//input[@type='text']";
export const tab_Additionaldetails ="//td[@id='fTb_C01']";
export const cmb_Pregnancyfirstcontacttype ="//input[@id='C2T_C4']";
export const txt_Gravida = "//input[@title='Please enter the number of pregnancies']";
export const txt_Gravida1 = "//input[@title='Please enter the number of live births']";
export const txt_Parity="//input[@title='Please enter the number of non-viable births']";
export const cmb_Pregnancyrisk = "//img[@title='Please select the pregnancy risk']";
export const cmb_FolicacidTaken ="//table[@id='C2_C28']//input[@type='text']";
export const tab_Additionaldetails ="//div[@id='ifS_C0']//td[@caption='Additional details']";
export const cmb_Pregnancyfirstconclstacttype ="//img[@title='Select the first contact type for this pregnancy']";
export const rad_Medicalcondtions = "//img[@id='iO_I_C9_1']";
export const cmb_ispartnetfatherofbaby = "//input[@id='C2T_C14']";
export const btn_Yes ="//img[@id='ic_I_C0']";
export const rad_PreviousCervicalsmear ="//a[@id='iO_A_C9_1' and normalize-space()='No']";
