// pageECCreateAttendance
export const lbl_ArrivalDate = "//label[@title = 'Arrival date/time']";
export const txt_ArrivalDate = "//table[@title = 'Enter arrival date and time']/descendant::input";
export const txt_Complaint = "//input[@dikey = 'txtPresentingComplaint']";
export const lbl_AttendanceType = "//label[@title = 'Attendance type']";
export const cmb_AttendanceType = "//input[@title = 'Select type of attendance']";
export const lbl_ResponsibleCP = "//label[@title = 'Responsible care provider']";
export const btn_ResponsibleCP = "//img[@title = 'Search and select attending care provider']";
export const lbl_AttendanceSource = "//label[@title = 'Attendance source']";
export const cmb_AttendanceSource = "//input[@title = 'Select the attendance source']";
export const lbl_ConsultationMedium = "//label[@title = 'Consultation medium']";
export const cmb_ConsultationMedium = "//input[@title = 'Select the Consultation medium']";
export const lbl_AssignedTo = "//label[@title = 'Assigned to']";
export const cmb_AssignedTo = "//input[@title = 'Select who patient is assigned to ']";
export const lbl_TimeElapsed = "//label[@title = 'Time elapsed']";
export const cmb_TimeElapsed = "//input[@title = 'Select time elapsed']";
export const lbl_PatientGrp = "//label[@title = 'Patient group']";
export const cmb_PatientGrp = "//input[@title = 'Select patient group ']";
export const lbl_ModeofArrival = "//label[@title= 'Mode of arrival']";
export const cmb_ModeofArrival = "//input[@title = 'Select how patient arrived in the department ']";
export const lbl_Area = "//label[@title= 'Area']";
export const btn_Area = "//img[@title= 'Click to select the area, sub area or location']";
export const lbl_AssociateReferral = "//label[@title = 'Associate referral']";
export const cmb_AssociateReferral = "//input[@title = 'Select type of referral association']";
export const lbl_AdminCategory = "//label[@title= 'Admin category']";
export const cmb_AdminCategory = "//input[@accesskey = 'Y']";
export const btn_Finish = "//td[@title= 'Finish']";
export const lbl_AccompaniedBy = "//label[@title = 'Accompanied by']";
export const txt_AccompaniedBy = "//input[@title = 'Enter the accompanied by']";
export const lbl_ReasonforModification = "//label[@title = 'Reason for modification']";
export const cmb_ReasonforModification = "//input[@title = 'Select reason for modification']";
