// pageAppWizard - Auto-generated by Click Recorder
// Generated: 2026-05-10T14:31:07.019Z
// Updated: 2026-05-10 - Added robust selectors for wizard buttons

// Finish now - try td[@title] first (more reliable), then span text
export const lbl_Finishnow = "//td[@title='Finish now'] | (//span[normalize-space(text())='Finish now'])[1]";
export const btn_Finishnow = "//td[@title='Finish now']";
export const span_Finishnow = "(//span[normalize-space(text())='Finish now'])[1]";

// Next button
export const lbl_Next = "//td[@title='Next'] | (//span[normalize-space(text())='Next'])[1]";
export const btn_Next = "//td[@title='Next']";

// Finish button (different from "Finish now")
export const lbl_Finish = "//td[@title='Finish'] | (//span[normalize-space(text())='Finish'])[1]";
export const btn_Finish = "//td[@title='Finish']";

// Previous button
export const btn_Previous = "//td[@title='Previous']";

// Cancel button
export const btn_Cancel = "//td[@title='Cancel']";

// Suspend button
export const btn_Suspend = "//td[@title='Suspend']";
