// pageTheatreManagement
export const txt_SessionStatusdefaultPlanned = "//div[@title='Planned']";
export const txt_SessionStatus = "//ion-label[contains(.,'<variable>')]/parent::ion-item/ion-checkbox";
export const btn_OKSessionStatus = "//ion-button[contains(.,'Ok')]";
export const lbl_TheatreSuite = "//ion-label[contains(.,'Theatre suite')]/ancestor::ion-card-header/following-sibling::ion-card-content/ion-item";
export const txt_TheatreSuite = "//ion-label[normalize-space()='<variable>']/ancestor::ion-item[1]/ion-radio";
export const btn_Cancel = "//ion-button[normalize-space()='Cancel']";
export const btn_Find = "//ion-button[normalize-space()='Find']";
export const btn_Clear = "//ion-button[normalize-space()='Clear']";
export const icn_Theatresession = "//tr[@class='k-master-row k-table-row']//span[@title='Ends every day session']";
export const tbl_Hubicon = "(//div[@title='<variable>']/ancestor::tr[@kendogridlogicalrow]/td/div[@part='calenderIcon'])[1]";
export const btn_NOW = "//ion-button[normalize-space()='NOW']";
export const lbl_TheatreSessionTABName = "//ion-segment-button//ion-label[normalize-space()='<variable>']/ancestor::ion-segment-button";
export const btn_OPStartedNOW = "//ion-label[normalize-space()='started']/ancestor::ion-card-header/following-sibling::ion-card-content//ion-button[normalize-space()='NOW']";
export const btn_OPEndNOW = "//ion-label[normalize-space()='end']/ancestor::ion-card-header/following-sibling::ion-card-content//ion-button[normalize-space()='NOW']";
export const txt_RecoveryWarning = "//ion-label[normalize-space()='warning']/ancestor::ion-card-header/following-sibling::ion-card-content//ion-input";
export const btn_Close = "//ion-button[normalize-space()='Close']";
export const txt_Reason = "//ion-label[normalize-space()='<variable>']/ancestor::ion-item[1]/ion-radio";
export const btn_ReasonOK = "//ion-button[contains(.,'OK')]";
export const btn_OkManagedelay = "//ion-button[contains(.,'Ok')]";
export const icn_Anaesthsia = '//body//app-root//ion-segment-button[2]';
export const icn_Operation = "//ion-segment-button[.//ion-label[normalize-space()='Operation']]";
export const btn_Menuicon = "//ion-button[@id='hub-menu']";
export const lnk_Manageoperation = "//ion-label[text()='Manage operation']";
export const btn_Addprocedure = "//ion-button[normalize-space(.)='Add procedure']";
export const txt_searchprocedure = '//cst-textbox//ion-input';
export const btn_Searchprocedure = "//ion-button[normalize-space()='Search']";
export const rad_procedureselect = "//div[contains(@class, 'radio-icon')]";
export const btn_okprocedure = "//ion-button[contains(@class, 'ok-btn') and contains(., 'Ok')]";
export const btn_Starttime = "//ion-button[contains(@class,'save-button') and contains(., 'OK')]";
export const btn_Okperformedby = "//ion-button[contains(@class,'save-button') and normalize-space(.)='OK']";
export const btn_Team = "//div[contains(@class, 'radio-icon')]";
export const btn_OKTeam = "//ion-button[@class='save-button manage_ops_save md button button-small button-solid ion-activatable ion-focusable hydrated']";
export const btn_Ok_Manageoperation = "//ion-button[normalize-space(text())='OK']";
export const txt_Starttime = "//input[contains(@class,'native-input') and @type='tel'][1]";
export const txt_Endtime = "//input[contains(@class,'native-input') and @type='tel'][2]";
export const btn_copytime = "//ion-button[contains(., 'Copy times to procedure')]";
export const txt_performedby = "//td[@data-kendo-grid-column-index='7']";
export const btn_performedby = "//div[contains(@class, 'radio-icon')]";
export const icn_Recovery = "//ion-segment-button[.//ion-label[normalize-space()='Recovery']]";
export const icn_Departure = "//ion-segment-button[.//ion-label[normalize-space()='Departure']]";
export const rad_Reason = "//ion-item[.//ion-label[normalize-space()='Nursing team delay']]//input";
export const btn_OK = "//ion-button[normalize-space()='OK']";
export const lbl_Comments = "//td[@role='gridcell' and @data-kendo-grid-column-index='4' and @aria-selected='true']";
export const txt_Commentstxt = "//textarea[@id='ion-textarea-3']";
export const btn_TheatreClose = "//ion-button[normalize-space()='Close']";
export const icn_Expand = "//td[@data-kendo-grid-column-index='9']//span[contains(@class,'mdi-chevron-right')]";
export const lnk_Theatreeventoverview = "//ion-label[.//span[normalize-space()='Theatre event overview']]";
export const txt_Actualstarttime = "//ion-col[normalize-space()='24/03/2026 07:45']";
export const txt_Actualendtime = "//ion-col[normalize-space()='25/03/2026 11:33']";
export const tab_Operation = "//ion-segment-button[@title='Operation']";
export const txt_verifyprocedure = "//div[normalize-space()='Ablation of inner ear by cryosurgery']";
export const btn_Logouttheatre = "//ion-button[@title='Log out']";
export const btn_Logoutbutton = "//ion-item[normalize-space()='Log out']";
export const btn_Logout = "//img[@title='Exit']";
export const txt_Yes = "//td[@title='Yes']";
