ï»¿export const tbl_IPHistorySelectRow= "//td[img[@alt='Click to select row']]";
export const tbl_tbl_IPHistoryVerifystatus = "//td[@ival='Booked']";
export const tbl_IPHistoryCurrentview = "//td[@caption='Current View']";
export const tab_InpatientHistory = "//td[@key='TB_PEGHISTORY']";
export const tbl_IPHistorySelectRowBktoAdmit = "//td[@headers='CtlParHeader0'][@align='left'][text()='Admitted']";
export const tbl_IPHistorySelectRowAdmit = "//td[@class='G_DRO G_WB_BA G_CP' and text()='Admitted']";
export const tbl_IPHistoryVerifystatus = "(//td[@icn='Event'])[1]";
export const txt_ValidationstatusAdmit = "//td[@ival='Admitted']";
export const  txt_Admissiondate = "(//td[@class='Adt_Activity_RowData' and @width='30%'])[8]";
export const tbl_IPHistorySelectRowAdmittoM = "//td[@icn='Event' and text()='Admitted']";
export const txt_Transfer = "//td[@ival='Actual Location Transfer']";
export const txt_WardValidate = "//td[text()='Psychiatry Building, Psychiatry IP Ward']";
export const txt_CPTransfer = "//td[@ival='Actual Careprovider Transfer']";
export const txt_CPValidate = "//td[@ival='Automation User515, ACCIDENT AND EMERGENCY, ACCIDENT AND EMERGENCY']";
export const tbl_IPHistorySelectRowloctran = "(//td[img[@alt='Click to select row']])[1]";
export const tbl_IPHistorySelectRowCPtran = "(//td[img[@alt='Click to select row']])[2]";
export const tbl_IPHistorySelectRowpatleave ="//td[contains(@class,'G_DRO')][contains(text(),'Informal Patient leave')]";
export const tbl_IPHistorySelectRowlevretn = "(//td[img[@alt='Click to select row']])[1]";
export const txt_Leaveretrun = "//td[@ival='Patient leave return']";
export const tbl_IPHistorymedicaldischarge = "//td[@ival='Medically discharged']";
export const txt_Discharge = "//td[@ival='Discharged']";
export const tbl_IPHistoryByHeader = "//tr[@id='g_TRColHdrC0']/ancestor::table[1]";
export const tbl_IPHistoryVerifystatus = "//td[@ival='Booked']";
export const tbl_IPHistorySelectRow= "//td[img[@alt='Click to select row']]";
