//pageInpatientmedication
// pagePrint Note from export
export const btn_Searchmedication = "//span[@title='Search']";
export const txt_MedicationSearch = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const lnk_searchdrug = "//button[normalize-space()='Search drug catalogue']";
export const txt_Drugcatelogue = "//kendo-gridlayout-item//span[normalize-space(text())='paracetamol']";
export const lnk_Selectitem = "//div[@title='Select item']";
export const icn_greenicon = "(//img[contains(@src, 'icopyacrossnor24.png')])[2]";
export const icn_greeniconmed1 = "(//img[contains(@src, 'icopyacrossnor24.png')])[3]";
//export const icn_greeniconmed2 = "(//img[contains(@src, 'icopyacrossnor24.png')])[3]";
export const icn_greeniconmed3 = "(//img[contains(@src, 'icopyacrossnor24.png')])[2]";
export const txt_medication = "(//div[@class='ng-star-inserted']//textblock[.//span[contains(text(),'paracetamol')]])[1]";
export const cmb_Route = "//icombobox[@name='cboRoute']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const cmb_Dosageform = "//icombobox[@ng-reflect--tooltip='Specify dosage form']//input[@role='combobox']";
//export const cmb_Dosetype1 = "(//span[contains(@class,'k-i-arrow-s')])[5]";
export const cmb_Dosetype = "//*[normalize-space()='Dose type']/following::input[@role='combobox'][1]";
export const cmb_Frequecymed3 = "//*[normalize-space()='Frequency']/following::input[@role='combobox'][1]";
export const cmb_Dose = "//kendo-gridlayout-item[@name='DoseLayoutRoot']//kendo-gridlayout-item[1]";
export const cmb_UOM = "//icombobox[@name='cboUOM']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const Cmb_Strength = "//icombobox[@name='cboStrength']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const cmb_Frequency = "//icombobox[@name='cboFrequency']//span[@class='k-button-icon k-icon k-i-arrow-s']";
export const btn_OK = "//button[normalize-space()='Ok']";
export const txt_MedicationSearch2 = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const txt_Drugcatelogue2 = "//kendo-gridlayout-item//span[normalize-space()='senna']";
export const txt_medication2 = "(//div[@class='ng-star-inserted']//textblock[.//span[contains(text(),'senna')]])[1]";
export const txt_medication3 = "(//div[@class='ng-star-inserted']//textblock[.//span[contains(text(),'flucloxacillin')]])[1]";
export const txt_Dose = "//kendo-gridlayout-item[@name='DoseLayoutRoot']//kendo-gridlayout-item[1]";
export const btn_Finish = "//span[normalize-space()='Finish']";
export const btn_Administrativetime1 = "(//kendo-label[normalize-space()='00:00'])[1]";
export const btn_Scheduled = "//gridcelltemplate[@ng-reflect-column-number='0']//kendo-label[@name='lblScheduled']";
//export const txt_Administrativetime1 = "(//kendo-label[normalize-space()='00:00'])[1]";
export const txt_AdminTimePicker = "//kendo-grid//input[contains(@id,'timepicker')]";
//export const dte_Administrativetime3 = "(//kendo-label[normalize-space()='00:00'])[5]";
//export const dte_Administrativetime4 = "(//kendo-label[normalize-space()='00:00'])[7]";
export const lbl_popup_conflict = "//div[@class='messageBoxContentborder']";
export const btn_OKpopup = "//span[@title='Ok']";
export const lbl_selectreason = "(//kendo-label[@title='Select reason'])[1]";
export const cmb_selectreason1 = "//kendo-label[@title='Clinically appropriate' and normalize-space()='Clinically appropriate']";
export const txt_Dose1 = "(//input[@role='spinbutton'])[1]";
export const txt_Dose2 = "(//input[@role='spinbutton'])[2]";
export const cmb_ModClerkReason = "//*[normalize-space()='Medication clerking modify reason']/following::kendo-searchbar[1]//input[@role='combobox']";
export const cmb_doserangecheck = "//*[normalize-space()='Acknowledgement reason']/following::kendo-searchbar[1]//input[@role='combobox']";
export const lnk_Conflicts = "/span[@title='Conflicts' and normalize-space()='Conflicts']";
export const btn_OK_10 = "//button[normalize-space()='Ok']";
export const lbl_DruRound = "//kendo-label[@name='lblDruRound']";
export const txt_MedicationSearch4 = "//kendo-textbox//input[contains(@class,'k-input-inner')]";
export const txt_Drugcatelogue4 = "(//kendo-gridlayout-item[@ng-reflect-col='2']//div[@title='Select item' and contains(@class,'link-Icon')])[1]";
export const rad_BeginsWith = "//iradiobutton//span//kendo-label[@title='Begins with']";
export const lnk_searchdrug = "//button[normalize-space()='Search drug catalogue']";
