// pageCreateuser
export const txt_UserSurname = "//input[@dikey='txtSurname']";
export const txt_UserForename = "//input[@dikey='txtForename']";
export const cmb_Title = "//input[@dikey='txtForeName']";
export const cmb_Identifiertype = "//img[@title='Select the type of identifier for the user']";
export const cmb_Identifiercode = "//input[@title='Enter the identifier for the user']";
export const icn_Add = "//td[@title='Click to add identifiers of the user']";
export const chk_mainidentifier = "//img[@id='iCI_C3' and @alt='Select if its the main identifer']";
export const btn_Next = "//td[@title='Next']";
export const icn_SFSOrg = "//img[@title='Select the Health organisation of user']";
export const txt_IdentifierOrg = "//img[@alt='Select if its the main identifer']";
export const btn_OK = "//td[@title='Click to Ok']";
export const cmb_Roletype = "//img[@id='icombobox_Image_C9' and @title='RoleProfiletype']";
export const icn_SFSRole = "//img[@title='Click to search and select role' and @alt='Launch search screen']";
export const txt_Displayname = "//input[@id='it_C_C5' and @title='Allows you to search roles based on display name']";
export const icn_SFSSpeciality = "ï¿½//img[@title='Allow you to search speciality of specific type']";
export const txt_Specialityname = "ï¿½//input[@title='Allows you to search on a Clinical unit name']";
export const btn_Find = "ï¿½//td[@title='Click to find']";
export const chk_Speciality = "ï¿½(//img[@title='Check the value'])[1]";
export const chk_Treatmentfunction = "ï¿½(//img[@title='Check the value'])[3]";
export const chk_Specialitychk = "ï¿½(//td[@title='Select Clinical unit(s) to assign to the role profile']//input[@type='checkbox'])[1]";
export const chk_Treatmentfunctionchk = "ï¿½(//td[@title='Select Clinical unit(s) to assign to the role profile']//input[@type='checkbox'])[2]";
export const chk_Isdefault = "ï¿½//img[@alt='Select, if it is default Role Profile']";
export const icn_Add1 = "ï¿½//td[@title='Click to add the newly created role profile to the grid']";
export const cmb_Logintype = "ï¿½//img[@title='Select login type']";
export const cmb_Openidprovider = "ï¿½//img[@title='Select OpenID Provider']";
export const cmb_Clientname = "//img[@title='Select client name']";
export const txt_Login = "//input[@dikey='txtLoginId']";
export const btn_Add = "//td[@title='Click to add']";
export const popup_email = "//input[@dikey='txtLoginId']";
export const txt_Email = "//input[@dikey='txtEmail']";
export const btn_Finish = "//span[normalize-space()='F']";
export const popup_Temppwd = "//div[@id='txtMessage']";
export const btn_OK2 = "//td[@title='Ok']";
